addons:
  postgresql: 10.5
language: ruby
rvm:
  - 2.5.1
script:
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
services:
  - postgresql
  - redis-server
